person:
  lastName: zhangsan
  age: 18
  boss: false
  bitrh: 2018/11/30
  maps: {k1: v1,k2: v2}
  lists:
    - lisi
    - zhaoliu
  dog:
    name: 小狗
    age: 2
server:
  port: 8081

#激活
spring:
  profiles:
    active: prod


---
server:
  port: 8082
spring:
  profiles: dev



---
server:
  port: 8083
spring:
  profiles: prod